#!/bin/bash

# This script was used while developing the test (this means that the
# script is not maintained and it is not supposed to be used to run
# tests).

readonly JUJAR="../junit-4.10.jar"
readonly EJAR="$HOME/.m2/repository/org/ekstazi/org.ekstazi.core/5.3.0/org.ekstazi.core-5.3.0.jar"

# Clean.
rm -rf .ekstazi

# Compile v0.
javac -cp "${JUJAR}" MyTestRunner.java CTest.java C1.java

# Run v0.
java -javaagent:"${EJAR}"=mode=junit \
     -cp "${JUJAR}:." \
     org.junit.runner.JUnitCore CTest

# Run v0 again.
java -javaagent:${EJAR}=mode=junit \
     -cp "${JUJAR}:." \
     org.junit.runner.JUnitCore CTest

# Compile v1.
javac -cp "${JUJAR}" MyTestRunner.java CTest.java C2.java

# Run v1.
java -javaagent:"${EJAR}"=mode=junit \
     -cp "${JUJAR}:." \
     org.junit.runner.JUnitCore CTest
